/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  /**
   * / Delete the entry for a given key (no-op if the key does not exist).
   */
  'deleteContent' : ActorMethod<[string], undefined>,
  /**
   * / Return all key-value pairs currently stored.
   */
  'getAllContent' : ActorMethod<[], Array<[string, string]>>,
  /**
   * / Retrieve the value for a given key. Returns null if not found.
   */
  'getContent' : ActorMethod<[string], [] | [string]>,
  /**
   * / Save or overwrite a value for the given key.
   */
  'saveContent' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];